### ISSUE TITLE
Assigning large points to outFile.points occurs error

### ISSUE THREAD

**Issue by swchoi06** [laspy/laspy#111]
While I was merging multi las files in one, I found a bug.

```
inFile = File('/path/to/file.las', mode='r')

outFile = File('/path/to/output.las', mode='w', header=inFile.header)
outFile.points = inFile.points[I]
outFile.close()
```

The above code works on small data points, but occur error on large data points (specifically over 2147483648, which is 2^31). 

Error code is 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/laspy/file.py", line 283, in set_points
    self._writer.set_points(new_points)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/laspy/base.py", line 1265, in set_points
    self.pad_file_for_point_recs(len(points))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/laspy/base.py", line 1125, in pad_file_for_point_recs
    self.data_provider.fileref.write(b"\x00" * (bytes_to_pad))
OSError: [Errno 22] Invalid argument
```

The problem was python built-in open function. Below code occurs same error. (maybe only for writing bytes string, I hadn't tested for str)

```
length = 2147483648 # or more
test_file = open('test.data', 'wb')
test_file.write(b"\x00" * length)
```

The solution is pretty simple, don't write it at once and split.

```
length = 2147483648
test_file = open('test.data', 'wb')
test_file.write(b"\x00" * length / 2)
test_file.write(b"\x00" * length / 2)
```

Of course, it would be better to use // %% or divmod. 

If it is ok, I can fixed the code and make pull request.

**Comment by hobu** [comment]
> If it is ok, I can fixed the code and make pull request.

That'd be great
