### ISSUE TITLE
Suddenly unable to read LAZ files

### ISSUE THREAD

**Issue by mwil** [laspy/laspy#112]
I think I was able to read LAZ files properly, but suddenly I get this error for exactly the same files. I am unsure what changed. laspy version is 1.5.1.

```
  File "src/las.py", line 239, in <module>
    analyze_las(ARGS.lasfile)
  File "src/las.py", line 163, in analyze_las
    inlas = laspy.file.File(lasfile, mode='r')
  File "/home/mwil/.cache/pypoetry/virtualenvs/dmp-py3.6/lib/python3.6/site-packages/laspy/file.py", line 64, in __init__
    self.open()
  File "/home/mwil/.cache/pypoetry/virtualenvs/dmp-py3.6/lib/python3.6/site-packages/laspy/file.py", line 75, in open
    self._reader = base.Reader(self.filename, mode=self._mode)
  File "/home/mwil/.cache/pypoetry/virtualenvs/dmp-py3.6/lib/python3.6/site-packages/laspy/base.py", line 273, in __init__
    self.setup_read_write(vlrs,evlrs, read_only=True)
  File "/home/mwil/.cache/pypoetry/virtualenvs/dmp-py3.6/lib/python3.6/site-packages/laspy/base.py", line 321, in setup_read_write
    self.data_provider.point_map()
  File "/home/mwil/.cache/pypoetry/virtualenvs/dmp-py3.6/lib/python3.6/site-packages/laspy/base.py", line 163, in point_map
    offset=self.manager.header.data_offset)
TypeError: a bytes-like object is required, not 'FakeMmap'
``

**Comment by mwil** [comment]
I also tried 1.7.0 52c9ad9, the error line moves to

```
Traceback (most recent call last):
  File ".\src\dmptools\dmptools\ushr\io\las.py", line 239, in <module>
    analyze_las(ARGS.lasfile)
  File ".\src\dmptools\dmptools\ushr\io\las.py", line 163, in analyze_las
    inlas = laspy.file.File(lasfile, mode='r')
  File "c:\users\dmpmatthiaswilhelm\appdata\local\pypoetry\cache\virtualenvs\ushrconvert-py3.7\src\laspy\laspy\file.py", line 64, in __init__
    self.open()
  File "c:\users\dmpmatthiaswilhelm\appdata\local\pypoetry\cache\virtualenvs\ushrconvert-py3.7\src\laspy\laspy\file.py", line 75, in open
    self._reader = base.Reader(self.filename, mode=self._mode)
  File "c:\users\dmpmatthiaswilhelm\appdata\local\pypoetry\cache\virtualenvs\ushrconvert-py3.7\src\laspy\laspy\base.py", line 318, in __init__
    self.setup_read_write(vlrs,evlrs, read_only=True)
  File "c:\users\dmpmatthiaswilhelm\appdata\local\pypoetry\cache\virtualenvs\ushrconvert-py3.7\src\laspy\laspy\base.py", line 366, in setup_read_write
    self.data_provider.point_map()
  File "c:\users\dmpmatthiaswilhelm\appdata\local\pypoetry\cache\virtualenvs\ushrconvert-py3.7\src\laspy\laspy\base.py", line 204, in point_map
    offset=self.manager.header.data_offset)
TypeError: a bytes-like object is required, not 'FakeMmap'
```

**Comment by mwil** [comment]
Moving closer to the solution, it works with numpy 1.16.4 but fails with numpy 1.17.

**Comment by NickVaughn** [comment]
You guys are probably already on it, but just as an FYI, I got it to work with numpy 1.17 with the simple change below. Not sure if this breaks with numpy < 1.17.

base.py:
```
143              _pmap = np.frombuffer(self._mmap, self.pointfmt,
to 
143              _pmap = np.frombuffer(self._mmap.__buffer__, self.pointfmt,
```

**Comment by chaitanyach** [comment]
> You guys are probably already on it, but just as an FYI, I got it to work with numpy 1.17 with the simple change below. Not sure if this breaks with numpy < 1.17.
> 
> base.py:
> 
> ```
> 143              _pmap = np.frombuffer(self._mmap, self.pointfmt,
> to 
> 143              _pmap = np.frombuffer(self._mmap.__buffer__, self.pointfmt,
> ```

It worked when I made the same change in line 163 instead of 143

**Comment by kbevers** [comment]
Please open a pull request with this change

**Comment by chaitanyach** [comment]
This should be tested with different numpy versions.

**Comment by bw4sz** [comment]
Can anyone confirm the required numpy version, i'm seeing this with 

```
import numpy
numpy.__version__
'1.18.1'
```

**Comment by bw4sz** [comment]
I downgraded to numpy 1.16.4 and it worked.

**Comment by csotomon** [comment]
I have the same issue, i had to downgrade numpy to 1.16.6 version

**Comment by Nukul13** [comment]
> Can anyone confirm the required numpy version, i'm seeing this with
> 
> ```
> (test) MacBook-Pro:NEON_crown_maps ben$ python
> Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:05:27)
> [Clang 9.0.1 ] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import laspy
> >>> laspy.__version__
> '1.6.0'
> ```
> 
> ```
> import numpy
> numpy.__version__
> '1.18.1'
> ```

Yes, this setup worked for me by making the changes on the line 163

**Comment by jeffsp** [comment]
I added the changes by @NickVaughn and @chaitanyach (lines 143 and 163), and while this fixed my read(), it then broke when I tried to write().

It looks like np.frombuffer wants to read from `_mmap.__buffer__` when opened in readonly mode, and it wants to read from `_mmap` when opened in append mode. I added a `try/except` around the problem lines to read from one when the other fails, and that fixes it... but that's a really cheesy solution, not suitable for a PR.

**Comment by kbevers** [comment]
> but that's a really cheesy solution, not suitable for a PR.

If it works, it works. Don't be ashamed of your solution. We would love to see a PR with a fix for this issue!

**Comment by mwil** [comment]
From the numpy 1.17 release notes:

> Do not lookup __buffer__ attribute in numpy.frombuffer
> Looking up __buffer__ attribute in numpy.frombuffer was undocumented and non-functional. This code was removed. If needed, use frombuffer(memoryview(obj), ...) instead.

**Comment by tmontaigu** [comment]
Closing as #122 was merged in order to fix this
