### ISSUE TITLE
precision loss when save float64 to xyz values

### ISSUE THREAD

**Issue by HowcanoeWang** [laspy/laspy#222]
I could understand this may caused due to las using int32 to store points, but will it possible to save with more decimal places? e.g. save as -1890831 rather than -1891 in this case?
```python
>>> header = laspy.LasHeader(point_format=2, version="1.2") 
>>> las = laspy.LasData(header) 
>>> las.x = np.array([-18.9083118])
>>> las.x
<ScaledArrayView([-18.91])>
>>> las.points.array
array([(-1891, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)],
      dtype=[('X', '<i4'), ('Y', '<i4'), ('Z', '<i4'), ('intensity', '<u2'), ('bit_fields', 'u1'), ('raw_classification', 'u1'), ('scan_angle_rank', 'i1'), ('user_data', 'u1'), ('point_source_id', '<u2'), ('red', '<u2'), ('green', '<u2'), ('blue', '<u2')])

```

**Comment by tmontaigu** [comment]
Its the `header.scales` that controls the precision, So you would have to change that to
have more precision

```Python
>>> import numpy as np
>>> header = laspy.LasHeader()
>>> las = laspy.LasData(header)
>>> las.x = np.array([-18.9083118])
>>> las.x
<ScaledArrayView([-18.91])>
>>> las.X
array([-1891])
>>>
>>>
>>>
>>> header = laspy.LasHeader()
>>> header.scales = np.array([0.0001, 0.0001, 0.0001])
>>> las = laspy.LasData(header)
>>> las.x = np.array([-18.9083118])
>>> las.x
<ScaledArrayView([-18.9083])>
>>> las.X
array([-189083])
>>>
>>>
>>> # default scale
>>> laspy.LasHeader().scales
array([0.01, 0.01, 0.01])
```

However the smaller the scale is, the higher the precision will be but also the higher the saved integer will be
so you'll probably need also set a proper `header.offsets`.

```Python
>>> -18.9083118 - -19.0
0.09168820000000011
>>> header.offsets = np.array([-19.0, 0.0, 0.0])
>>> las = laspy.LasData(header)
>>> las.x = np.array([-18.9083118])
>>> las.x
<ScaledArrayView([-18.9083])>
>>> las.X
array([917])
```

**Comment by HowcanoeWang** [comment]
It seems I misunderstood the meaning of "scale", thank you for your detailed explanation! And if possible, please update this point in the documentation.

**Comment by HowcanoeWang** [comment]
PS, is there any method that can be used to auto decide the offset (precision)? Similiar with this issue: https://github.com/laspy/laspy/issues/201

```python
>>> import numpy as np
>>> import laspy     
>>> header = laspy.LasHeader(point_format=2, version="1.2")
>>> header.offsets = [ 367900., 3955800., 0.]    
>>> header.scales = [0.000001, 0.000001, 0.000001]  
>>> las = laspy.LasData(header) 
>>> las.header.offset
[367900.0, 3955800.0, 0.0]
>>> las.header.offsets
[367900.0, 3955800.0, 0.0]
>>> x = np.array( [ 93.0206,  93.146,   92.6317,  114.7912, 114.1528, 116.7278])  
>>> las.points['x'] = x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hwang\.conda\envs\easyidp\lib\site-packages\laspy\point\record.py", line 207, in __setitem__
    self[key][:] = value
  File "C:\Users\hwang\.conda\envs\easyidp\lib\site-packages\laspy\point\dims.py", line 788, in __setitem__
    raise OverflowError(
OverflowError: Values given do not fit after applying offset and scale
```

**Comment by HowcanoeWang** [comment]
Apologize for my bad English that made you confusing

> The error is saying that after saling your x into X by doing X = (x - header.x_offset) / header.x_scale

This helps me to solve my problem. I did not know it minus offset again in the backend.

I splited the `xyz_raw` = `xyz` + `offset`

And `header.offset = offset`, `las.xyz = xyz` caused the error, it can be fixed if I pass `las.xyz = xyz_raw` in my code.

Thanks again for your help!
