### ISSUE TITLE
Incorrect LAZ generated after converting point format

### ISSUE THREAD

**Issue by bacek** [laspy/laspy#233]
laspy produces incorrect laszip files after converting point format.

Examples with a simple test file 
```
>>> import laspy
>>> laspy.__version__
'2.2.0'
>>> o = laspy.read('test.laz')
>>> o.header.point_format
<PointFormat(3, 0 bytes of extra dims)>
>>> c = laspy.convert(o, point_format_id=8)
>>> c.write('converted.laz')
>>> reloaded = laspy.read('converted.laz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bacek/work/polez/conda/polez/lib/python3.9/site-packages/laspy/lib.py", line 187, in read_las
    return reader.read()
  File "/home/bacek/work/polez/conda/polez/lib/python3.9/site-packages/laspy/lasreader.py", line 115, in read
    points = self.read_points(-1)
  File "/home/bacek/work/polez/conda/polez/lib/python3.9/site-packages/laspy/lasreader.py", line 94, in read_points
    self.point_source.read_n_points(n), self.header.point_format
  File "/home/bacek/work/polez/conda/polez/lib/python3.9/site-packages/laspy/lasreader.py", line 379, in read_n_points
    self.decompressor.decompress_many(point_bytes)
pylaz.LazrsError: IoError: failed to fill whole buffer
```

pdal output for generated file:
```
dal info converted.laz 
(pdal info readers.las Error) Global encoding WKT flag not set for point format 6 - 10.
PDAL: readers.las: reading point 0 of 28 total points

```

It just throws an exception inside LasZip

Example with empty laz file.
```
>>> o = laspy.read('empty.laz')
>>> o.header.point_format
<PointFormat(3, 0 bytes of extra dims)>
>>> c = laspy.convert(o, point_format_id=8)
>>> c.write('converted.laz')
>>> reloaded = laspy.read('converted.laz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bacek/work/polez/conda/polez/lib/python3.9/site-packages/laspy/lib.py", line 187, in read_las
    return reader.read()
  File "/home/bacek/work/polez/conda/polez/lib/python3.9/site-packages/laspy/lasreader.py", line 119, in read
    source = self.point_source.source
AttributeError: 'EmptyPointReader' object has no attribute 'source'

```

**Comment by bacek** [comment]
Looks like this issue affects only lazrs version.

**Comment by tmontaigu** [comment]
So the problem is that lazrs doesnt correctly compress the files with point format 7 or 8 when either rgb or nir always contains the same value (0 in this example)

The problem is fixed locally and will require a new laz-rs version

**Comment by tmontaigu** [comment]
A new version of lazrs was published, it fixes this issue
