### ISSUE TITLE
install CSF on linux

### ISSUE THREAD

**Issue by Mengxi-Wang** [laspy/laspy#240]
Hi,

I've created a virtual environment laspy and install laspy in it, then I copied the source package CSF-master from github and installed in laspy environment, I listed the site-packages in this env. I've got this error when install CSF on Linux. 

(laspy) mengwang@bw20c109:~/laspy/lib/python3.8/site-packages$ ls
CSF-1.1.1-py3.8.egg-info             laszip.cpython-38-x86_64-linux-gnu.so  pkg_resources
CSF.py                               laszip.libs                            python_dateutil-2.8.2.dist-info
_CSF.cpython-38-x86_64-linux-gnu.so  numpy                                  pytz
__pycache__                          numpy-1.23.3.dist-info                 pytz-2022.2.1.dist-info
dateutil                             numpy.libs                             setuptools
easy_install.py                      pandas                                 setuptools-49.2.1.dist-info
laspy                                pandas-1.5.0.dist-info                 six-1.16.0.dist-info
laspy-2.2.0.dist-info                pip                                    six.py
laszip-0.1.0.dist-info               pip-22.2.2.dist-info
(laspy) mengwang@bw20c109:~/laspy/lib/python3.8/site-packages$ cd
(laspy) mengwang@bw20c109:~$ python3
Python 3.8.8 (default, Apr 13 2021, 19:58:26)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import CSF
Traceback (most recent call last):
  File "/home/mengwang/laspy/lib/python3.8/site-packages/CSF.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/mengwang/yes/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/mengwang/laspy/lib/python3.8/site-packages/_CSF.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mengwang/laspy/lib/python3.8/site-packages/CSF.py", line 17, in <module>
    _CSF = swig_import_helper()
  File "/home/mengwang/laspy/lib/python3.8/site-packages/CSF.py", line 16, in swig_import_helper
    return importlib.import_module('_CSF')
  File "/home/mengwang/yes/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/mengwang/laspy/lib/python3.8/site-packages/_CSF.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv

Any solutions? Thanks!

**Comment by tmontaigu** [comment]
Well laspy is not related to CSF in any way, shape or form so we can't help you

**Comment by Mengxi-Wang** [comment]
I'm so sorry I just noticed I went to a wrong place! I was about to the CSF page, and now the problem is fixed. Sorry for bothering you!

Kind regards,
Mengxi
________________________________
