### ISSUE TITLE
ValueError: buffer size must be a multiple of element size

### ISSUE THREAD

**Issue by pmaggiore** [laspy/laspy#242]
Hi,
while reading a file with laspy I'm encountering the following error

> >>> import laspy
> >>> las_file = laspy.read("file.las")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/jboss/wildfly-11.0.0.Final/server/djberepogr/anaconda3/lib/python3.7/site-packages/laspy/lib.py", line 187, in read_las
>     return reader.read()
>   File "/jboss/wildfly-11.0.0.Final/server/djberepogr/anaconda3/lib/python3.7/site-packages/laspy/lasreader.py", line 115, in read
>     points = self.read_points(-1)
>   File "/jboss/wildfly-11.0.0.Final/server/djberepogr/anaconda3/lib/python3.7/site-packages/laspy/lasreader.py", line 94, in read_points
>     self.point_source.read_n_points(n), self.header.point_format
>   File "/jboss/wildfly-11.0.0.Final/server/djberepogr/anaconda3/lib/python3.7/site-packages/laspy/point/record.py", line 126, in from_buffer
>     data = np.frombuffer(buffer, dtype=points_dtype, offset=offset, count=count)
> ValueError: buffer size must be a multiple of element size

Actually I'm switching from the old pylas to laspy and pylas is able to read this file.
I don't know if laspy can be updated in order to not receive this kind of error and still be able to read the file.
Sadly I can't share the lidar file; let me know if it's needed more info by my side.

**Comment by tmontaigu** [comment]
I would need the file version point format, and how many bytes the file is in total.

Likely what is happening is that the files is incomplete (file bytes != header size + (num points * point_size).

And from what I remember, pylas is probably truncating the file when it detect that and log a warning

**Comment by tmontaigu** [comment]
I'd also need the `offset_to_point_data`

**Comment by pmaggiore** [comment]
- offset_to_point_data: 229

**Comment by tmontaigu** [comment]
So your file does have a problem,

78_856_192 - 229 = 78_855_963 bytes for all the points in the file.

78_855_963 / 4_139_840 = 19.04807021527402 bytes per points, which does not make sense, this number should be without decimals

For point format 3 we expect 34 bytes per points.


pylas 0.4.3 would also raise an error for this file.

pylas 0.6.0a2 reads the file without error, however it cannot read missing bytes.
What  happens, and what you shoud likely see after reading the file with pylas 0.6.0a2 it that 
points after point index 2_319_293 are all zeros

**Comment by pmaggiore** [comment]
Thank you for the explanation! 
I'll try to investigate the reason why I received this problematic file.
Do you think it wouldn't be correct to be able to read the available bytes anyway?

**Comment by tmontaigu** [comment]
Well, for uncompressed filed (LAS), what we could do is detect if we read less bytes than expected is correcting so that the point suze is a multiplier of `corrected_len`.

However for LAZ it might a bit more tricky.

And it does not change the fact the the file has a problem, so the user should at least be notified somehow,

This would need some thinking to chose what we do

This is similar to the problem is #
