### ISSUE TITLE
Open laz fh.read() with error mid > len

### ISSUE THREAD

**Issue by vincentBenet** [laspy/laspy#328]
I have the code inside a QGIS python console outside QGIS using python-qgis-ltr.bat (this is why i need to install from inside script)...
  
```
  import pip
  pip.main(["install", "pylas[lazrs,laszip]"])
  path = layer_cloud.source()  // QGIS pointCloud layer ending with laz but not copc format
  with pylas.open(path) as fh:
      print('Points from Header:', fh.header.point_count)
      las = fh.read()
```

Then I got the following error:

```
  Points from Header: 430883977
  WARNING: There are 2 bytes between end of vlrs and start of points
  thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\laz-0.9.2\src\byteslice.rs:34:43:
  mid > len
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  Traceback (most recent call last):
    File "C:\Users\VincentBenet\AppData\Roaming\QGIS\QGIS3\profiles\vince\python\plugins\qgis_to_drone_flight_plan\tracks\run.py", line 326, in cloud_to_polygon
      las = fh.read()
    File "C:\Users\VincentBenet\AppData\Roaming\Python\Python39\site-packages\pylas\lasreader.py", line 64, in read
      points = self._read_points(vlrs)
    File "C:\Users\VincentBenet\AppData\Roaming\Python\Python39\site-packages\pylas\lasreader.py", line 114, in _read_points
      points = self._read_compressed_points_data(laszip_vlr, point_format)
    File "C:\Users\VincentBenet\AppData\Roaming\Python\Python39\site-packages\pylas\lasreader.py", line 136, in _read_compressed_points_data
      decompressed_points = lazrs_decompress_buffer(
    File "C:\Users\VincentBenet\AppData\Roaming\Python\Python39\site-packages\pylas\compression.py", line 64, in lazrs_decompress_buffer
      lazrs.decompress_points(point_compressed, vlr_data, point_decompressed, parallel)
  pyo3_runtime.PanicException: mid > len
```

My file is heavy (4Go) so I can t share it.
This is a laz file that is loaded correctly by QGIS

**Comment by tmontaigu** [comment]
Without access to the file, chances of getting this fixed are close to 0% I think

**Comment by tmontaigu** [comment]
Thanks, I'll investigate the issue

**Comment by tmontaigu** [comment]
Hum, I can read the file without problems, you should try to upgrade lazrs
