### ISSUE TITLE
Error mapping file: [Errno 22] Invalid argument: when opening LAS file

### ISSUE THREAD

**Issue by fri-end** [laspy/laspy#56]
Hi,

I'm using laspy 1.4.2 installed via conda on Ubuntu 14.04 and I'm getting following error when trying to open LAS file (see [link](https://www.dropbox.com/sh/dj04kt4c60x9d32/AABWKAt_-e8n5hvTG4sK0qj3a?dl=0)):

`inFile = laspy.file.File('960.las', mode = "r")`

> Traceback (most recent call last):
  File "/home/friend/PycharmProjects/fm/var_calc.py", line 23, in <module>
    inFile = laspy.file.File('960.las', mode = "r")
  File "/home/friend/miniconda2/lib/python2.7/site-packages/laspy/file.py", line 63, in __init__
    self.open()
  File "/home/friend/miniconda2/lib/python2.7/site-packages/laspy/file.py", line 74, in open
    self._reader = base.Reader(self.filename, mode=self._mode)
  File "/home/friend/miniconda2/lib/python2.7/site-packages/laspy/base.py", line 250, in __init__
    self.setup_read_write(vlrs,evlrs, read_only=True)
  File "/home/friend/miniconda2/lib/python2.7/site-packages/laspy/base.py", line 307, in setup_read_write
    self.data_provider.remap(point_map = True)
  File "/home/friend/miniconda2/lib/python2.7/site-packages/laspy/base.py", line 199, in remap
    self.map()
  File "/home/friend/miniconda2/lib/python2.7/site-packages/laspy/base.py", line 191, in map
    raise laspy.util.LaspyException("Error mapping file: " + str(e))
laspy.util.LaspyException: Error mapping file: [Errno 22] Invalid argument

I would appreciate any help in solving this issue.
Thanks, Yuri

**Comment by kbevers** [comment]
No problem opening the file here. I need more information about your system in order to tell what is wrong. What version of numpy are you using? Have you tried updating all your python packages?

**Comment by fri-end** [comment]
I use numpy 1.11.2 and laspy 1.4.2 both installed via conda on Ubuntu 14.04
`conda update --all` didn't solve the issue
Is there anything else I can try?
