### ISSUE TITLE
laspy and python 3.5 (again...)

### ISSUE THREAD

**Issue by umbe1987** [laspy/laspy#61]
Hi,

I am kind of a fan of laspy since I recently discovered it and tried it with a few LAS files I have.
I now am in trouble because I am forced to use a python installation shipped with a GIS software (ArcGIS Pro), which is version 3.5. The reason is that it contains a module (arcpy) which is only present with this installation.

I am aware that laspy works with Python 2.7, but as suggested in issue #40 I tried to install the fork of GeospatialPython. Nevertheless, I failed to have it working though.
What I did was:

-     downloaded the zip from the forked repository and unzipped it to a directory (let's call it [DIR])
-     opened a cmd terminal with admin privileges (I'm on Win10) and cd to the root laspy directory (as explained in the docs)
-     did "python setup.py build"

I am sure I am using the right interpreter (the 3.5 shipped with ArcGIS Pro). After that, I received:

```
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import laspy
  File "C:\Umberto\lidar\laspy\geospatial_fork\laspy-master\laspy\__init__.py", line 3, in <module>
    import base
ImportError: No module named 'base'
```

Does anyone have any idea on what's going on? Is it because the laspy in the fork I am using is just compatible with python 3.4 and not 3.5? Or am I missing something else? Thanks in advance!

P.S. I would have added a new issue on the GeospatialPython repository, but I couldn't see any way to do that (my understanding of github is kind of basic...).

**Comment by umbe1987** [comment]
Found an answer in #40. (would have closed it via that issue, but I could not do it...).
