### ISSUE TITLE
ValueError: buffer is smaller than requested size

### ISSUE THREAD

**Issue by fredericbonifas** [laspy/laspy#91]
I am trying to open a LAS file in version 1.4, with laspy 1.5.1. Unfortunately, I cannot provide the file, but I can give some metadata if it helps.

```
import laspy
inlas = laspy.file.File("file.las.las", mode="r")
```
I get this error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fbs/dev/vegetation_encroachment/modelisation/venv3/lib/python3.6/site-packages/laspy/file.py", line 64, in __init__
    self.open()
  File "/home/fbs/dev/vegetation_encroachment/modelisation/venv3/lib/python3.6/site-packages/laspy/file.py", line 75, in open
    self._reader = base.Reader(self.filename, mode=self._mode)
  File "/home/fbs/dev/vegetation_encroachment/modelisation/venv3/lib/python3.6/site-packages/laspy/base.py", line 277, in __init__
    self.setup_read_write(vlrs,evlrs, read_only=True)
  File "/home/fbs/dev/vegetation_encroachment/modelisation/venv3/lib/python3.6/site-packages/laspy/base.py", line 325, in setup_read_write
    self.data_provider.point_map()
  File "/home/fbs/dev/vegetation_encroachment/modelisation/venv3/lib/python3.6/site-packages/laspy/base.py", line 180, in point_map
    count=self.manager.header.point_records_count)
ValueError: buffer is smaller than requested size
```
Looking at the `base.py` laspy file, I've found that the `point_map` function handles differently the LAS file according to their version. Removing the `count=self.manager.header.point_records_count` option of `np.frombuffer` fixes my problem: https://github.com/laspy/laspy/blob/master/laspy/base.py#L176

Is there any use for this option, or could it be removed?

**Comment by brycefrank** [comment]
I continue to have this issue with a file, even with the merged branch from #98, any updates?

**Comment by evelkey** [comment]
I've had the same issue and removing the above mentioned parameter helped and now it's working on all LAS files (1.3 version), I created a fork here: [fork without self.manager.header.point_records_count](https://github.com/NNstorm/laspy).

**Comment by tmontaigu** [comment]
I'm closing as I don't think the bug still exists in laspy 2.0.

If it still does, then we will reopen this issue and fix the bug.
